title: "Lew"
author: "Lew"
description: "Last updated 31 Aug 2024"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "research.md"}
  - {file: "teaching.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:noemail@gmail.com"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=AdxYcLkAAAAJ"}
  - {title: ORCID, icon: orcid, url: "https://orcid.org/0000-0003-1769-7898"}
  - {title: LinkedIn, icon: linkedin-in, url: "https://www.linkedin.com/in/zijian-lew-b0ab8626/"}
  - {title: X/Twitter, icon: x-twitter, url: "https://twitter.com/leuuzj"}
# you'll need to update the icons.json file before a new icon can be used. Give it a name and update the path based on fontawesome.com/icons 

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
